image: docker:latest
services:
  - docker:dind

variables:
  APP_NAME: mark-server
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  KUBE_VERSION: v1.18.6
  KUBECTL_URL: https://storage.googleapis.com/kubernetes-release/release/${KUBE_VERSION}/bin/linux/amd64/kubectl
  KUBE_NAMESPACE: jarvis-mark

stages:
  - build_container
  - deploy

cache:
  paths:
    - node_modules/
    - packages/server/node_modules/

build_container:
  stage: build_container
  environment:
    name: dev
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd packages/server/
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH' # Only trigger when changes occur in default branch
    - changes:
        - ./packages/server/** # Only trigger when changes occur in packages/server directory

deploy:
  stage: deploy
  environment:
    name: dev
  script:
    - apk add --no-cache curl libintl gettext
    - curl ${KUBECTL_URL} -o /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl
    - export KUBE_CONTEXT="bostonscientific.com/jarvis/jarvis-mark-s/mark-s:backend"
    - kubectl config use-context ${KUBE_CONTEXT}
    - kubectl kustomize k8s/backend/base | envsubst | kubectl apply -n ${KUBE_NAMESPACE} -f -
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH' # Only trigger when changes occur in default branch
    - changes:
        - ./packages/server/** # Only trigger when changes occur in k8s/backend directory
