image: docker:latest
services:
  - docker:dind

variables:
  APP_NAME: mark-server
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  KUBE_VERSION: v1.18.6
  KUBECTL_URL: https://storage.googleapis.com/kubernetes-release/release/${KUBE_VERSION}/bin/linux/amd64/kubectl
  KUBE_NAMESPACE: dhp

stages:
  - build_container
  - deploy

build_container:
  stage: build_container
  environment:
    name: dev
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd packages/server/
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  environment:
    name: dev
  script:
    - apk add --no-cache curl libintl gettext
    - curl ${KUBECTL_URL} -o /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl
    - kubectl kustomize k8s/dev | envsubst | kubectl apply -n ${KUBE_NAMESPACE} -f -
