---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APP_NAME}-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
spec:
  rules:
    # env = dev, staging or prod
    # set with gitlab environment
    - host: ${APP_NAME}.${CI_ENVIRONMENT_NAME}.apps.bsci.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${APP_NAME}-svc
                port:
                  number: 3000
