---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-svc
spec:
  ports:
    - port: 3000
      name: backend
      protocol: TCP
  selector:
    app: ${APP_NAME}

---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-admin-svc
spec:
  ports:
    - port: 3005
      name: admin
      protocol: TCP
  selector:
    app: ${APP_NAME}
