export const SliderData = [
  {
    Lower_bound_sales_achievement_percentage: 0,
    Upper_bound_sales_achievement_percentage: 90,
    Variable_payout_percentage: 0.0,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 90,
    Upper_bound_sales_achievement_percentage: 91,
    Variable_payout_percentage: 70.0,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 91,
    Upper_bound_sales_achievement_percentage: 92,
    Variable_payout_percentage: 73.0,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 92,
    Upper_bound_sales_achievement_percentage: 93,
    Variable_payout_percentage: 76.0,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 93,
    Upper_bound_sales_achievement_percentage: 94,
    Variable_payout_percentage: 79.0,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 94,
    Upper_bound_sales_achievement_percentage: 95,
    Variable_payout_percentage: 85.0,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 95,
    Upper_bound_sales_achievement_percentage: 96,
    Variable_payout_percentage: 87.5,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 96,
    Upper_bound_sales_achievement_percentage: 97,
    Variable_payout_percentage: 90.0,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 97,
    Upper_bound_sales_achievement_percentage: 98,
    Variable_payout_percentage: 94.0,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 98,
    Upper_bound_sales_achievement_percentage: 99,
    Variable_payout_percentage: 96.0,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 99,
    Upper_bound_sales_achievement_percentage: 100,
    Variable_payout_percentage: 98.0,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 100,
    Upper_bound_sales_achievement_percentage: 101,
    Variable_payout_percentage: 100.0,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 101,
    Upper_bound_sales_achievement_percentage: 102,
    Variable_payout_percentage: 101.0,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 102,
    Upper_bound_sales_achievement_percentage: 103,
    Variable_payout_percentage: 102.0,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 103,
    Upper_bound_sales_achievement_percentage: 104,
    Variable_payout_percentage: 103.5,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 104,
    Upper_bound_sales_achievement_percentage: 105,
    Variable_payout_percentage: 105.0,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 105,
    Upper_bound_sales_achievement_percentage: 106,
    Variable_payout_percentage: 106.5,
    Territory_category: 'A',
    Commission_percentage: 0.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 106,
    Upper_bound_sales_achievement_percentage: 116,
    Variable_payout_percentage: 106.5,
    Territory_category: 'A',
    Commission_percentage: 4.0,
  },
  {
    Lower_bound_sales_achievement_percentage: 116,
    Upper_bound_sales_achievement_percentage: 121,
    Variable_payout_percentage: 106.5,
    Territory_category: 'A',
    Commission_percentage: 4.1,
  },
  {
    Lower_bound_sales_achievement_percentage: 121,
    Upper_bound_sales_achievement_percentage: 126,
    Variable_payout_percentage: 106.5,
    Territory_category: 'A',
    Commission_percentage: 4.2,
  },
  {
    Lower_bound_sales_achievement_percentage: 126,
    Upper_bound_sales_achievement_percentage: 131,
    Variable_payout_percentage: 106.5,
    Territory_category: 'A',
    Commission_percentage: 4.3,
  },
  {
    Lower_bound_sales_achievement_percentage: 131,
    Upper_bound_sales_achievement_percentage: 136,
    Variable_payout_percentage: 106.5,
    Territory_category: 'A',
    Commission_percentage: 4.4,
  },
  {
    Lower_bound_sales_achievement_percentage: 136,
    Upper_bound_sales_achievement_percentage: 141,
    Variable_payout_percentage: 106.5,
    Territory_category: 'A',
    Commission_percentage: 4.5,
  },
  {
    Lower_bound_sales_achievement_percentage: 141,
    Upper_bound_sales_achievement_percentage: 146,
    Variable_payout_percentage: 106.5,
    Territory_category: 'A',
    Commission_percentage: 4.6,
  },
  {
    Lower_bound_sales_achievement_percentage: 146,
    Upper_bound_sales_achievement_percentage: 9999,
    Variable_payout_percentage: 106.5,
    Territory_category: 'A',
    Commission_percentage: 4.7,
  },
];
