import {CalendarUtils} from 'react-native-calendars';
import {ItemPlanResponse} from 'network/apis/plan/PlanResponse';

const EVENT_COLOR = '#e6add8';
const today = new Date();
export const getDate = (offset = 0) =>
  CalendarUtils.getCalendarDateString(
    new Date().setDate(today.getDate() + offset),
  );

export const timelineEvents: ItemPlanResponse[] = [
  {
    start: `${getDate()} 01:15:00`,
    end: `${getDate()} 03:30:00`,
    id: '1',
    status: 1,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
    duration: '120 Minutes',
  },
  {
    start: `${getDate()} 03:30:00`,
    end: `${getDate()} 05:30:00`,
    id: '1',
    status: 2,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
    duration: '120 Minutes',
  },
  {
    start: `${getDate()} 05:40:00`,
    end: `${getDate()} 07:00:00`,
    id: '1',
    status: 3,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
    duration: '120 Minutes',
  },
  {
    start: `${getDate()} 07:40:00`,
    end: `${getDate()} 09:10:00`,
    id: '1',
    status: 4,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
    duration: '120 Minutes',
  },
  {
    start: `${getDate()} 10:50:00`,
    end: `${getDate()} 12:20:00`,
    id: '1',
    status: 1,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
    duration: '120 Minutes',
  },
  {
    start: `${getDate()} 13:30:00`,
    end: `${getDate()} 15:30:00`,
    id: '1',
    status: 1,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
    duration: '120 Minutes',
  },
  {
    start: `${getDate(1)} 00:30:00`,
    end: `${getDate(1)} 01:30:00`,
    id: '1',
    status: 1,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
    duration: '120 Minutes',
  },
  {
    start: `${getDate(1)} 02:30:00`,
    end: `${getDate(1)} 03:20:00`,
    id: '1',
    status: 1,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
    duration: '120 Minutes',
  },
  {
    start: `${getDate(1)} 04:10:00`,
    end: `${getDate(1)} 04:40:00`,
    id: '1',
    status: 1,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
    duration: '120 Minutes',
  },
  {
    start: `${getDate(1)} 01:05:00`,
    end: `${getDate(1)} 01:35:00`,
    id: '1',
    status: 1,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
  },
  {
    start: `${getDate(1)} 14:30:00`,
    end: `${getDate(1)} 16:30:00`,
    id: '1',
    status: 1,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
  },
  {
    start: `${getDate(2)} 01:40:00`,
    end: `${getDate(2)} 02:25:00`,
    id: '1',
    status: 1,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
  },
  {
    start: `${getDate(2)} 04:10:00`,
    end: `${getDate(2)} 04:40:00`,
    id: '1',
    status: 1,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
    duration: '120 Minutes',
  },
  {
    start: `${getDate(2)} 00:45:00`,
    end: `${getDate(2)} 01:45:00`,
    id: '1',
    status: 1,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
    duration: '120 Minutes',
  },
  {
    start: `${getDate(2)} 11:30:00`,
    end: `${getDate(2)} 12:30:00`,
    id: '1',
    status: 1,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
    duration: '120 Minutes',
  },
  {
    start: `${getDate(4)} 12:10:00`,
    end: `${getDate(4)} 13:45:00`,
    id: '1',
    status: 1,
    title: 'Operation ABC',
    desc: 'AAA Hospital',
    duration: '120 Minutes',
  },
];
