bases:
  - ../../base
patches:
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: ${APP_NAME}-ingress
    path: ingress-patch-dev.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ${APP_NAME}
    path: deployment-patch-dev.yaml
