import { objectType } from 'nexus'

export const Sales = objectType({
  nonNullDefaults: {
    output: true,
    input: false,
  },
  name: 'Sales',
  definition(t) {
    t.int('id')
    t.nullable.string('salesRepEmail')
    t.nullable.string('sipEligibility')
    t.nullable.string('currency')
    t.nullable.string('year')
    t.nullable.string('quarter')
    t.nullable.string('month')
    t.nullable.string('productType')
    t.nullable.string('newHire')
    t.nullable.string('guaranttedPayout')
    t.nullable.string('mixedBag')
    t.nullable.string('variablePayByMonth')
    t.nullable.string('variablePayByYear')
    t.nullable.string('variablePayByQuarter')
    t.nullable.string('variablePayQ5')
    t.nullable.string('salesByMonth')
    t.nullable.string('salesByYear')
    t.nullable.string('salesByQuarter')
    t.nullable.string('targetByMonth')
    t.nullable.string('targetByYear')
    t.nullable.string('targetByQuarter')
    t.nullable.string('salesAchievementPercentageByMonth')
    t.nullable.string('salesAchievementPercentageByYear')
    t.nullable.string('salesAchievementPercentageByQuarter')
    t.nullable.string('variablePayoutPercentageByQuarter')
    t.nullable.string('variablePayoutPercentageByYear')
    t.nullable.string('targetByYearUSD')
    t.nullable.string('territoryCategory')
    t.nullable.string('commissionPercentageByQuarter')
    t.nullable.string('commissionPayoutByQuarter')
    t.nullable.string('variablePayoutByQuarter')
    t.nullable.string('additionalPayout')
    t.nullable.string('kicker')
    t.nullable.string('earlyBirdEligibility')
    t.nullable.string('earlyBird')
    t.nullable.string('variablePayoutPercentageQ5')
    t.nullable.string('variablePayoutQ5')
    t.nullable.string('commissionPercentageQ5')
    t.nullable.string('commissionPayoutQ5')
    t.nullable.string('salesByMonth_forNewHire')
    t.nullable.string('salesByYear_forNewHire')
    t.nullable.string('salesByQuarter_forNewHire')
    t.nullable.string('salesAchivementPercentageByQuarter_forNewHire')
    t.nullable.string('salesAchievementPercentageByYear_forNewHire')
    t.nullable.string('variablePayoutPercentageByQuarter_forNewHire')
    t.nullable.string('variablePayoutPercentageQ5_forNewHire')
    t.nullable.string('commissionPercentageByQuarter_forNewHire')
    t.nullable.string('commissionPercentageQ5_forNewHire')
    t.nullable.string('variablePayoutByQuarter_forNewHire')
    t.nullable.string('variablePayoutQ5_forNewHire')
    t.nullable.string('commissionPayoutByQuarter_forNewHire')
    t.nullable.string('commissionPayoutQ5_forNewHire')
    t.nullable.string('additionalPayoutCE')
    t.nullable.string('additionalPayoutSC')
    t.nullable.field('createdAt', { type: 'DateTime' })
    t.nullable.field('updatedAt', { type: 'DateTime' })
  },
})
