version: '3.7'
services:
  nest-api:
    container_name: nest-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./src/common:/app/src/common
      - ./src/modules:/app/src/modules
      - ./src/@generated:/app/src/@generated
      - ./src:/app/src
      - ./dist:/app/dist
      - ./prisma:/app/prisma
      - "./node_modules/.prisma:/app/node_modules/.prisma"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
