/* eslint-disable global-require */
/**
* @author GNURT
* @flow
*/

const images = {
  LoadingScreen: require('../assets/images/LoadingScreen.png'),
  ic_add: require('../assets/images/ic_add.png'),
  ic_agenda: require('../assets/images/ic_agenda.png'),
  ic_avatar: require('../assets/images/ic_avatar.png'),
  ic_back: require('../assets/images/ic_back.png'),
  ic_bg_avatar: require('../assets/images/ic_bg_avatar.png'),
  ic_boost: require('../assets/images/ic_boost.png'),
  ic_boost_with_bg: require('../assets/images/ic_boost_with_bg.png'),
  ic_booster: require('../assets/images/ic_booster.png'),
  ic_case: require('../assets/images/ic_case.png'),
  ic_case_log: require('../assets/images/ic_case_log.png'),
  ic_chart: require('../assets/images/ic_chart.png'),
  ic_chart2: require('../assets/images/ic_chart2.png'),
  ic_checked: require('../assets/images/ic_checked.png'),
  ic_circleCalendar: require('../assets/images/ic_circleCalendar.png'),
  ic_clock: require('../assets/images/ic_clock.png'),
  ic_close: require('../assets/images/ic_close.png'),
  ic_coin: require('../assets/images/ic_coin.png'),
  ic_complaint: require('../assets/images/ic_complaint.png'),
  ic_contact: require('../assets/images/ic_contact.png'),
  ic_day: require('../assets/images/ic_day.png'),
  ic_dislike: require('../assets/images/ic_dislike.png'),
  ic_doctor_default: require('../assets/images/ic_doctor_default.png'),
  ic_dolar: require('../assets/images/ic_dolar.png'),
  ic_dolar2: require('../assets/images/ic_dolar2.png'),
  ic_down: require('../assets/images/ic_down.png'),
  ic_dropdown: require('../assets/images/ic_dropdown.png'),
  ic_editProfile: require('../assets/images/ic_editProfile.png'),
  ic_face: require('../assets/images/ic_face.png'),
  ic_filter: require('../assets/images/ic_filter.png'),
  ic_filter2: require('../assets/images/ic_filter2.png'),
  ic_goldMedal: require('../assets/images/ic_goldMedal.png'),
  ic_home: require('../assets/images/ic_home.png'),
  ic_hospital: require('../assets/images/ic_hospital.png'),
  ic_info: require('../assets/images/ic_info.png'),
  ic_leaderBoard: require('../assets/images/ic_leaderBoard.png'),
  ic_leader_board_gold: require('../assets/images/ic_leader_board_gold.png'),
  ic_leader_with_bg: require('../assets/images/ic_leader_with_bg.png'),
  ic_like: require('../assets/images/ic_like.png'),
  ic_like_grey: require('../assets/images/ic_like_grey.png'),
  ic_location: require('../assets/images/ic_location.png'),
  ic_logo: require('../assets/images/ic_logo.png'),
  ic_logoLeaderBoard: require('../assets/images/ic_logoLeaderBoard.png'),
  ic_logout: require('../assets/images/ic_logout.png'),
  ic_mail: require('../assets/images/ic_mail.png'),
  ic_month: require('../assets/images/ic_month.png'),
  ic_phone: require('../assets/images/ic_phone.png'),
  ic_plan: require('../assets/images/ic_plan.png'),
  ic_plan_with_bg: require('../assets/images/ic_plan_with_bg.png'),
  ic_plus: require('../assets/images/ic_plus.png'),
  ic_profile: require('../assets/images/ic_profile.png'),
  ic_profileAvatar: require('../assets/images/ic_profileAvatar.png'),
  ic_rating_gold: require('../assets/images/ic_rating_gold.png'),
  ic_rating_unselected: require('../assets/images/ic_rating_unselected.png'),
  ic_recent: require('../assets/images/ic_recent.png'),
  ic_recent2: require('../assets/images/ic_recent2.png'),
  ic_sale: require('../assets/images/ic_sale.png'),
  ic_sales_call: require('../assets/images/ic_sales_call.png'),
  ic_scanBarcode: require('../assets/images/ic_scanBarcode.png'),
  ic_search: require('../assets/images/ic_search.png'),
  ic_setting: require('../assets/images/ic_setting.png'),
  ic_sharing: require('../assets/images/ic_sharing.png'),
  ic_sort: require('../assets/images/ic_sort.png'),
  ic_statusCancel: require('../assets/images/ic_statusCancel.png'),
  ic_three_day: require('../assets/images/ic_three_day.png'),
  ic_time: require('../assets/images/ic_time.png'),
  ic_top1: require('../assets/images/ic_top1.png'),
  ic_top2: require('../assets/images/ic_top2.png'),
  ic_top3: require('../assets/images/ic_top3.png'),
  ic_total: require('../assets/images/ic_total.png'),
  ic_user: require('../assets/images/ic_user.png'),
  ic_view_file: require('../assets/images/ic_view_file.png'),
  ic_whitePlus: require('../assets/images/ic_whitePlus.png'),
  ic_x: require('../assets/images/ic_x.png'),
  img_background: require('../assets/images/img_background.png'),
  img_logo: require('../assets/images/img_logo.png'),
};
export default images;
