// import { Account } from "@prisma/client";

// type ActualAccount = Omit<
//   Account,
//   "id" | "createdAt" | "updatedAt" | "accountId"
// > & {
//   divisions: DIVISION[];
// };

// export const accounts: ActualAccount[] = [
//   {
//     accountName: "Hospital 1",
//     addressCity: "Los Angeles",
//     addressPostalCode: "90001",
//     addressState: "California",
//     addressStreet: "5678 Elm Street",

//     country: "United States",
//     divisions: [DIVISION.CRM, DIVISION.IC],
//     email: "",
//     phone: "987-654-3210",
//     website: "https://www.hospital1.com",
//     status: "Active",
//     longitude: 34.0522,
//     latitude: -118.2437,
//   },
//   {
//     accountName: "Hospital 2",
//     addressCity: "New York",
//     addressPostalCode: "10001",
//     addressState: "New York",
//     addressStreet: "7890 Oak Avenue",
//     country: "United States",
//     divisions: [DIVISION.LAAC, DIVISION.PI],
//     email: "",
//     phone: "123-789-4560",
//     website: "https://www.hospital2.com",
//     status: "Active",
//     longitude: 40.7128,
//     latitude: -74.006,
//   },
//   {
//     accountName: "Hospital 3",
//     addressCity: "Chicago",
//     addressPostalCode: "60601",
//     addressState: "Illinois",
//     addressStreet: "1234 Maple Lane",
//     country: "United States",
//     divisions: [DIVISION.UROPH, DIVISION.TAVR],
//     email: "",
//     phone: "456-123-7890",
//     website: "https://www.hospital3.com",
//     status: "Active",
//     longitude: 41.8781,
//     latitude: -87.6298,
//   },
//   {
//     accountName: "Hospital 4",
//     addressCity: "Houston",
//     addressPostalCode: "77001",
//     addressState: "Texas",
//     addressStreet: "5678 Oak Street",
//     country: "United States",
//     divisions: [DIVISION.AC],
//     email: "",
//     phone: "789-456-1230",
//     website: "https://www.hospital4.com",
//     status: "Active",
//     longitude: 29.7604,
//     latitude: -95.3698,
//   },
//   {
//     accountName: "Hospital 5",
//     addressCity: "Miami",
//     addressPostalCode: "33101",
//     addressState: "Florida",
//     addressStreet: "4321 Pine Road",
//     country: "United States",
//     divisions: [DIVISION.ENDO, DIVISION.NM],
//     email: "",
//     phone: "654-321-9870",
//     website: "https://www.hospital5.com",
//     status: "Active",
//     longitude: 25.7617,
//     latitude: -80.1918,
//   },
//   // {
//   //   accountName: "Hospital 6",
//   //   addressCity: "San Diego",
//   //   addressPostalCode: "92101",
//   //   addressState: "California",
//   //   addressStreet: "8765 Cedar Avenue",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.CRM, DIVISION.LAAC],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital6.com",
//   //   status: "Active",
//   //   longitude: 32.7157,
//   //   latitude: -117.1611,
//   // },
//   // {
//   //   accountName: "Hospital 7",
//   //   addressCity: "Dallas",
//   //   addressPostalCode: "75201",
//   //   addressState: "Texas",
//   //   addressStreet: "2345 Birch Lane",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.PI, DIVISION.UROPH],
//   //   email: "",
//   //
//   //   phone: "789-456-1230",
//   //   website: "https://www.hospital7.com",
//   //   status: "Active",
//   //   longitude: 32.7767,
//   //   latitude: -96.7970,
//   // },
//   // {
//   //   accountName: "Hospital 8",
//   //   addressCity: "Philadelphia",
//   //   addressPostalCode: "19101",
//   //   addressState: "Pennsylvania",
//   //   addressStreet: "3456 Oak Street",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.TAVR, DIVISION.AC],
//   //   email: "",
//   //
//   //   phone: "987-654-3210",
//   //   website: "https://www.hospital8.com",
//   //   status: "Active",
//   //   longitude: 39.9526,
//   //   latitude: -75.1652,
//   // },
//   // {
//   //   accountName: "Hospital 9",
//   //   addressCity: "Phoenix",
//   //   addressPostalCode: "85001",
//   //   addressState: "Arizona",
//   //   addressStreet: "6789 Pine Road",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.CRM, DIVISION.ENDO],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital9.com",
//   //   status: "Active",
//   //   longitude: 33.4484,
//   //   latitude: -112.0740,
//   // },
//   // {
//   //   accountName: "Hospital 10",
//   //   addressCity: "Seattle",
//   //   addressPostalCode: "98101",
//   //   addressState: "Washington",
//   //   addressStreet: "9876 Elm Avenue",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.LAAC, DIVISION.PI],
//   //   email: "",
//   //
//   //   phone: "789-456-1230",
//   //   website: "https://www.hospital10.com",
//   //   status: "Active",
//   //   longitude: 47.6062,
//   //   latitude: -122.3321,
//   // },
//   // {
//   //   accountName: "Hospital 11",
//   //   addressCity: "Boston",
//   //   addressPostalCode: "02101",
//   //   addressState: "Massachusetts",
//   //   addressStreet: "5432 Cedar Lane",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.UROPH, DIVISION.TAVR],
//   //   email: "",
//   //
//   //   phone: "987-654-3210",
//   //   website: "https://www.hospital11.com",
//   //   status: "Active",
//   //   longitude: 42.3601,
//   //   latitude: -71.0589,
//   // },
//   // {
//   //   accountName: "Hospital 12",
//   //   addressCity: "San Jose",
//   //   addressPostalCode: "95101",
//   //   addressState: "California",
//   //   addressStreet: "2345 Pine Road",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.AC],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital12.com",
//   //   status: "Active",
//   //   longitude: 37.3541,
//   //   latitude: -121.9552,
//   // },
//   // {
//   //   accountName: "Hospital 13",
//   //   addressCity: "Austin",
//   //   addressPostalCode: "73301",
//   //   addressState: "Texas",
//   //   addressStreet: "8765 Birch Avenue",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.CRM, DIVISION.IC],
//   //   email: "",
//   //
//   //   phone: "789-456-1230",
//   //   website: "https://www.hospital13.com",
//   //   status: "Active",
//   //   longitude: 30.2672,
//   //   latitude: -97.7431,
//   // },
//   // {
//   //   accountName: "Hospital 14",
//   //   addressCity: "Denver",
//   //   addressPostalCode: "80201",
//   //   addressState: "Colorado",
//   //   addressStreet: "3456 Oak Lane",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.PI, DIVISION.NM],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital14.com",
//   //   status: "Active",
//   //   longitude: 39.7392,
//   //   latitude: -104.9903,
//   // },
//   // {
//   //   accountName: "Hospital 15",
//   //   addressCity: "Nashville",
//   //   addressPostalCode: "37201",
//   //   addressState: "Tennessee",
//   //   addressStreet: "6789 Cedar Street",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.UROPH, DIVISION.TAVR],
//   //   email: "",
//   //
//   //   phone: "789-456-1230",
//   //   website: "https://www.hospital15.com",
//   //   status: "Active",
//   //   longitude: 36.1627,
//   //   latitude: -86.7816,
//   // },
//   // {
//   //   accountName: "Hospital 16",
//   //   addressCity: "Atlanta",
//   //   addressPostalCode: "30301",
//   //   addressState: "Georgia",
//   //   addressStreet: "1234 Elm Road",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.AC],
//   //   email: "",
//   //
//   //   phone: "987-654-3210",
//   //   website: "https://www.hospital16.com",
//   //   status: "Active",
//   //   longitude: 33.7489,
//   //   latitude: -84.3879,
//   // },
//   // {
//   //   accountName: "Hospital 17",
//   //   addressCity: "Orlando",
//   //   addressPostalCode: "32801",
//   //   addressState: "Florida",
//   //   addressStreet: "5678 Pine Lane",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.CRM, DIVISION.ENDO],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital17.com",
//   //   status: "Active",
//   //   longitude: 28.5383,
//   //   latitude: -81.3792,
//   // },
//   // {
//   //   accountName: "Hospital 18",
//   //   addressCity: "Las Vegas",
//   //   addressPostalCode: "89101",
//   //   addressState: "Nevada",
//   //   addressStreet: "8765 Cedar Lane",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.LAAC, DIVISION.PI],
//   //   email: "",
//   //
//   //   phone: "789-456-1230",
//   //   website: "https://www.hospital18.com",
//   //   status: "Active",
//   //   longitude: 36.1699,
//   //   latitude: -115.1398,
//   // },
//   // {
//   //   accountName: "Hospital 19",
//   //   addressCity: "San Antonio",
//   //   addressPostalCode: "78201",
//   //   addressState: "Texas",
//   //   addressStreet: "2345 Oak Road",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.UROPH, DIVISION.TAVR],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital19.com",
//   //   status: "Active",
//   //   longitude: 29.4241,
//   //   latitude: -98.4936,
//   // },
//   // {
//   //   accountName: "Hospital 20",
//   //   addressCity: "San Francisco",
//   //   addressPostalCode: "94101",
//   //   addressState: "California",
//   //   addressStreet: "3456 Pine Avenue",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.AC],
//   //   email: "",
//   //
//   //   phone: "987-654-3210",
//   //   website: "https://www.hospital20.com",
//   //   status: "Active",
//   //   longitude: 37.7749,
//   //   latitude: -122.4194,
//   // },
//   // {
//   //   accountName: "Hospital 21",
//   //   addressCity: "Detroit",
//   //   addressPostalCode: "48201",
//   //   addressState: "Michigan",
//   //   addressStreet: "1234 Elm Street",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.CRM, DIVISION.IC],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital21.com",
//   //   status: "Active",
//   //   longitude: 42.3314,
//   //   latitude: -83.0458,
//   // },
//   // {
//   //   accountName: "Hospital 22",
//   //   addressCity: "New Orleans",
//   //   addressPostalCode: "70112",
//   //   addressState: "Louisiana",
//   //   addressStreet: "5678 Oak Lane",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.LAAC, DIVISION.PI],
//   //   email: "",
//   //
//   //   phone: "789-456-1230",
//   //   website: "https://www.hospital22.com",
//   //   status: "Active",
//   //   longitude: 29.9511,
//   //   latitude: -90.0715,
//   // },
//   // {
//   //   accountName: "Hospital 23",
//   //   addressCity: "Minneapolis",
//   //   addressPostalCode: "55401",
//   //   addressState: "Minnesota",
//   //   addressStreet: "8765 Pine Avenue",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.UROPH, DIVISION.TAVR],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital23.com",
//   //   status: "Active",
//   //   longitude: 44.9778,
//   //   latitude: -93.2650,
//   // },
//   // {
//   //   accountName: "Hospital 24",
//   //   addressCity: "Portland",
//   //   addressPostalCode: "97201",
//   //   addressState: "Oregon",
//   //   addressStreet: "2345 Cedar Road",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.AC],
//   //   email: "",
//   //
//   //   phone: "987-654-3210",
//   //   website: "https://www.hospital24.com",
//   //   status: "Active",
//   //   longitude: 45.5155,
//   //   latitude: -122.6793,
//   // },
//   // {
//   //   accountName: "Hospital 25",
//   //   addressCity: "St. Louis",
//   //   addressPostalCode: "63101",
//   //   addressState: "Missouri",
//   //   addressStreet: "3456 Elm Lane",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.CRM, DIVISION.IC],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital25.com",
//   //   status: "Active",
//   //   longitude: 38.6270,
//   //   latitude: -90.1994,
//   // },
//   // {
//   //   accountName: "Hospital 26",
//   //   addressCity: "Kansas City",
//   //   addressPostalCode: "64101",
//   //   addressState: "Missouri",
//   //   addressStreet: "1234 Oak Street",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.LAAC, DIVISION.PI],
//   //   email: "",
//   //
//   //   phone: "789-456-1230",
//   //   website: "https://www.hospital26.com",
//   //   status: "Active",
//   //   longitude: 39.0997,
//   //   latitude: -94.5786,
//   // },
//   // {
//   //   accountName: "Hospital 27",
//   //   addressCity: "Charlotte",
//   //   addressPostalCode: "28201",
//   //   addressState: "North Carolina",
//   //   addressStreet: "5678 Cedar Avenue",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.UROPH, DIVISION.TAVR],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital27.com",
//   //   status: "Active",
//   //   longitude: 35.2271,
//   //   latitude: -80.8431,
//   // },
//   // {
//   //   accountName: "Hospital 28",
//   //   addressCity: "Raleigh",
//   //   addressPostalCode: "27601",
//   //   addressState: "North Carolina",
//   //   addressStreet: "8765 Oak Lane",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.AC],
//   //   email: "",
//   //
//   //   phone: "987-654-3210",
//   //   website: "https://www.hospital28.com",
//   //   status: "Active",
//   //   longitude: 35.7796,
//   //   latitude: -78.6382,
//   // },
//   // {
//   //   accountName: "Hospital 29",
//   //   addressCity: "Indianapolis",
//   //   addressPostalCode: "46201",
//   //   addressState: "Indiana",
//   //   addressStreet: "2345 Pine Avenue",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.CRM, DIVISION.IC],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital29.com",
//   //   status: "Active",
//   //   longitude: 39.7684,
//   //   latitude: -86.1581,
//   // },
//   // {
//   //   accountName: "Hospital 30",
//   //   addressCity: "Columbus",
//   //   addressPostalCode: "43201",
//   //   addressState: "Ohio",
//   //   addressStreet: "3456 Elm Road",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.LAAC, DIVISION.PI],
//   //   email: "",
//   //
//   //   phone: "789-456-1230",
//   //   website: "https://www.hospital30.com",
//   //   status: "Active",
//   //   longitude: 39.9612,
//   //   latitude: -82.9988,
//   // },
//   // {
//   //   accountName: "Hospital 31",
//   //   addressCity: "Cleveland",
//   //   addressPostalCode: "44101",
//   //   addressState: "Ohio",
//   //   addressStreet: "1234 Cedar Street",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.UROPH, DIVISION.TAVR],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital31.com",
//   //   status: "Active",
//   //   longitude: 41.4993,
//   //   latitude: -81.6944,
//   // },
//   // {
//   //   accountName: "Hospital 32",
//   //   addressCity: "Pittsburgh",
//   //   addressPostalCode: "15201",
//   //   addressState: "Pennsylvania",
//   //   addressStreet: "5678 Oak Road",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.AC],
//   //   email: "",
//   //
//   //   phone: "987-654-3210",
//   //   website: "https://www.hospital32.com",
//   //   status: "Active",
//   //   longitude: 40.4406,
//   //   latitude: -79.9959,
//   // },
//   // {
//   //   accountName: "Hospital 33",
//   //   addressCity: "Hartford",
//   //   addressPostalCode: "06101",
//   //   addressState: "Connecticut",
//   //   addressStreet: "8765 Cedar Avenue",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.CRM, DIVISION.IC],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital33.com",
//   //   status: "Active",
//   //   longitude: 41.7658,
//   //   latitude: -72.6734,
//   // },
//   // {
//   //   accountName: "Hospital 34",
//   //   addressCity: "Baltimore",
//   //   addressPostalCode: "21201",
//   //   addressState: "Maryland",
//   //   addressStreet: "2345 Pine Road",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.LAAC, DIVISION.PI],
//   //   email: "",
//   //
//   //   phone: "789-456-1230",
//   //   website: "https://www.hospital34.com",
//   //   status: "Active",
//   //   longitude: 39.2904,
//   //   latitude: -76.6122,
//   // },
//   // {
//   //   accountName: "Hospital 35",
//   //   addressCity: "Salt Lake City",
//   //   addressPostalCode: "84101",
//   //   addressState: "Utah",
//   //   addressStreet: "3456 Oak Street",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.UROPH, DIVISION.TAVR],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital35.com",
//   //   status: "Active",
//   //   longitude: 40.7608,
//   //   latitude: -111.8910,
//   // },
//   // {
//   //   accountName: "Hospital 36",
//   //   addressCity: "San Juan",
//   //   addressPostalCode: "00901",
//   //   addressState: "Puerto Rico",
//   //   addressStreet: "6789 Elm Lane",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.AC],
//   //   email: "",
//   //
//   //   phone: "987-654-3210",
//   //   website: "https://www.hospital36.com",
//   //   status: "Active",
//   //   longitude: 18.4663,
//   //   latitude: -66.1057,
//   // },
//   // {
//   //   accountName: "Hospital 37",
//   //   addressCity: "Honolulu",
//   //   addressPostalCode: "96801",
//   //   addressState: "Hawaii",
//   //   addressStreet: "1234 Oak Avenue",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.CRM, DIVISION.IC],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital37.com",
//   //   status: "Active",
//   //   longitude: 21.3069,
//   //   latitude: -157.8583,
//   // },
//   // {
//   //   accountName: "Hospital 38",
//   //   addressCity: "Anchorage",
//   //   addressPostalCode: "99501",
//   //   addressState: "Alaska",
//   //   addressStreet: "5678 Pine Avenue",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.LAAC, DIVISION.PI],
//   //   email: "",
//   //
//   //   phone: "789-456-1230",
//   //   website: "https://www.hospital38.com",
//   //   status: "Active",
//   //   longitude: 61.2181,
//   //   latitude: -149.9003,
//   // },
//   // {
//   //   accountName: "Hospital 39",
//   //   addressCity: "Albuquerque",
//   //   addressPostalCode: "87101",
//   //   addressState: "New Mexico",
//   //   addressStreet: "8765 Cedar Road",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.UROPH, DIVISION.TAVR],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital39.com",
//   //   status: "Active",
//   //   longitude: 35.0844,
//   //   latitude: -106.6504,
//   // },
//   // {
//   //   accountName: "Hospital 40",
//   //   addressCity: "Boise",
//   //   addressPostalCode: "83701",
//   //   addressState: "Idaho",
//   //   addressStreet: "2345 Elm Lane",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.AC],
//   //   email: "",
//   //
//   //   phone: "987-654-3210",
//   //   website: "https://www.hospital40.com",
//   //   status: "Active",
//   //   longitude: 43.6150,
//   //   latitude: -116.2023,
//   // },
//   // {
//   //   accountName: "Hospital 41",
//   //   addressCity: "Des Moines",
//   //   addressPostalCode: "50301",
//   //   addressState: "Iowa",
//   //   addressStreet: "3456 Cedar Avenue",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.CRM, DIVISION.IC],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital41.com",
//   //   status: "Active",
//   //   longitude: 41.6005,
//   //   latitude: -93.6091,
//   // },
//   // {
//   //   accountName: "Hospital 42",
//   //   addressCity: "Oklahoma City",
//   //   addressPostalCode: "73101",
//   //   addressState: "Oklahoma",
//   //   addressStreet: "1234 Oak Road",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.LAAC, DIVISION.PI],
//   //   email: "",
//   //
//   //   phone: "789-456-1230",
//   //   website: "https://www.hospital42.com",
//   //   status: "Active",
//   //   longitude: 35.4634,
//   //   latitude: -97.5151,
//   // },
//   // {
//   //   accountName: "Hospital 43",
//   //   addressCity: "Memphis",
//   //   addressPostalCode: "38101",
//   //   addressState: "Tennessee",
//   //   addressStreet: "5678 Elm Street",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.UROPH, DIVISION.TAVR],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital43.com",
//   //   status: "Active",
//   //   longitude: 35.1495,
//   //   latitude: -90.0490,
//   // },
//   // {
//   //   accountName: "Hospital 44",
//   //   addressCity: "Louisville",
//   //   addressPostalCode: "40201",
//   //   addressState: "Kentucky",
//   //   addressStreet: "8765 Pine Road",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.AC],
//   //   email: "",
//   //
//   //   phone: "987-654-3210",
//   //   website: "https://www.hospital44.com",
//   //   status: "Active",
//   //   longitude: 38.2527,
//   //   latitude: -85.7585,
//   // },
//   // {
//   //   accountName: "Hospital 45",
//   //   addressCity: "Jackson",
//   //   addressPostalCode: "39201",
//   //   addressState: "Mississippi",
//   //   addressStreet: "2345 Cedar Avenue",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.CRM, DIVISION.IC],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital45.com",
//   //   status: "Active",
//   //   longitude: 32.2988,
//   //   latitude: -90.1848,
//   // },
//   // {
//   //   accountName: "Hospital 46",
//   //   addressCity: "Wichita",
//   //   addressPostalCode: "67201",
//   //   addressState: "Kansas",
//   //   addressStreet: "3456 Oak Lane",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.LAAC, DIVISION.PI],
//   //   email: "",
//   //
//   //   phone: "789-456-1230",
//   //   website: "https://www.hospital46.com",
//   //   status: "Active",
//   //   longitude: 37.6860,
//   //   latitude: -97.3356,
//   // },
//   // {
//   //   accountName: "Hospital 47",
//   //   addressCity: "Little Rock",
//   //   addressPostalCode: "72201",
//   //   addressState: "Arkansas",
//   //   addressStreet: "1234 Elm Lane",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.UROPH, DIVISION.TAVR],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital47.com",
//   //   status: "Active",
//   //   longitude: 34.7465,
//   //   latitude: -92.2896,
//   // },
//   // {
//   //   accountName: "Hospital 48",
//   //   addressCity: "Tulsa",
//   //   addressPostalCode: "74101",
//   //   addressState: "Oklahoma",
//   //   addressStreet: "5678 Oak Road",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.AC],
//   //   email: "",
//   //
//   //   phone: "987-654-3210",
//   //   website: "https://www.hospital48.com",
//   //   status: "Active",
//   //   longitude: 36.1540,
//   //   latitude: -95.9928,
//   // },
//   // {
//   //   accountName: "Hospital 49",
//   //   addressCity: "Omaha",
//   //   addressPostalCode: "68101",
//   //   addressState: "Nebraska",
//   //   addressStreet: "8765 Cedar Street",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.CRM, DIVISION.IC],
//   //   email: "",
//   //
//   //   phone: "123-789-4560",
//   //   website: "https://www.hospital49.com",
//   //   status: "Active",
//   //   longitude: 41.2565,
//   //   latitude: -95.9345,
//   // },
//   // {
//   //   accountName: "Hospital 50",
//   //   addressCity: "Honolulu",
//   //   addressPostalCode: "96801",
//   //   addressState: "Hawaii",
//   //   addressStreet: "2345 Pine Road",
//   //
//   //   country: "United States",
//   //   DIVISION: [DIVISION.LAAC, DIVISION.PI],
//   //   email: "",
//   //
//   //   phone: "789-456-1230",
//   //   website: "https://www.hospital50.com",
//   //   status: "Active",
//   //   longitude: 21.3069,
//   //   latitude: -157.8583,
//   // },
// ];
