// import { Contact, DivisionalContact } from "@prisma/client";

// type ActualContact = Omit<
//   Contact,
//   "id" | "createdAt" | "updatedAt" | "accountId" | "middleName"
// > & {
//   divisionalContact: Omit<DivisionalContact, "id" | "contactId">;
// };

// export const contacts: ActualContact[] = [
//   {
//     firstName: "Alice",
//     lastName: "Smith",
//     preferredName: "Ali",
//     title: "Manager",
//     designation: "Designation 1",
//     department: "Department 1",
//     contactNumber: "987-654-3210",
//     primaryBusinessEmail: "alice@example.com",
//     secondaryBusinessEmail: "alice.secondary@example.com",
//     alternativeEmail: "alice.alt@example.com",
//     profilePhoto: "profile-photo-url",
//     topicsOfInterest: ["Topic 3", "Topic 4"],
//     division: "Division 1",
//     specialty: "Specialty 2",
//     country: "USA",
//     divisionalContact: {
//       contactName: "John Doe",
//       division: "Division 1",
//       function: "Function 1",
//       phone: "123-456-7890",
//       specialty: "Specialty 1",
//       subSpecialty: "SubSpecialty 1",
//       topicsOfInterest: ["Topic 1", "Topic 2"],
//     },
//   },
//   {
//     firstName: "Bob",
//     lastName: "Johnson",
//     preferredName: "Bobby",
//     title: "Director",
//     designation: "Designation 2",
//     department: "Department 2",
//     contactNumber: "555-555-5555",
//     primaryBusinessEmail: "bob@example.com",
//     secondaryBusinessEmail: "bob.secondary@example.com",
//     alternativeEmail: "bob.alt@example.com",
//     profilePhoto: "profile-photo-url",
//     topicsOfInterest: ["Topic 1", "Topic 2"],
//     division: "Division 2",
//     specialty: "Specialty 1",
//     country: "USA",
//     divisionalContact: {
//       contactName: "Jane Doe",
//       division: "Division 2",
//       function: "Function 2",
//       phone: "123-456-7890",
//       specialty: "Specialty 2",
//       subSpecialty: "SubSpecialty 2",
//       topicsOfInterest: ["Topic 3", "Topic 4"],
//     },
//   },
//   {
//     firstName: "Charlie",
//     lastName: "Brown",
//     preferredName: "Chuck",
//     title: "Manager",
//     designation: "Designation 3",
//     department: "Department 3",
//     contactNumber: "123-456-7890",
//     primaryBusinessEmail: "charlie@example.com",
//     secondaryBusinessEmail: "",
//     alternativeEmail: "",
//     profilePhoto: "",
//     topicsOfInterest: ["Topic 1", "Topic 2"],
//     division: "Division 3",
//     specialty: "Specialty 1",
//     country: "USA",
//     divisionalContact: {
//       contactName: "John Smith",
//       division: "Division 3",
//       function: "Function 3",
//       phone: "123-456-7890",
//       specialty: "Specialty 2",
//       subSpecialty: "SubSpecialty 3",
//       topicsOfInterest: ["Topic 3", "Topic 4"],
//     },
//   },
//   {
//     firstName: "David",
//     lastName: "Lee",
//     preferredName: "Dave",
//     title: "Director",
//     designation: "Designation 4",
//     department: "Department 4",
//     contactNumber: "123-456-7890",
//     primaryBusinessEmail: "david@example.com",
//     secondaryBusinessEmail: "",
//     alternativeEmail: "",
//     profilePhoto: "",
//     topicsOfInterest: ["Topic 3", "Topic 4"],
//     division: "Division 4",
//     specialty: "Specialty 2",
//     country: "USA",
//     divisionalContact: {
//       contactName: "Jane Smith",
//       division: "Division 4",
//       function: "Function 4",
//       phone: "123-456-7890",
//       specialty: "Specialty 1",
//       subSpecialty: "SubSpecialty 4",
//       topicsOfInterest: ["Topic 1", "Topic 2"],
//     },
//   },
//   {
//     firstName: "Emily",
//     lastName: "Wang",
//     preferredName: "Em",
//     title: "Manager",
//     designation: "Designation 5",
//     department: "Department 5",
//     contactNumber: "123-456-7890",
//     primaryBusinessEmail: "emily@example.com",
//     secondaryBusinessEmail: "",
//     alternativeEmail: "",
//     profilePhoto: "",
//     topicsOfInterest: ["Topic 1", "Topic 2"],
//     division: "Division 5",
//     specialty: "Specialty 1",
//     country: "USA",
//     divisionalContact: {
//       contactName: "John Lee",
//       division: "Division 5",
//       function: "Function 5",
//       phone: "123-456-7890",
//       specialty: "Specialty 2",
//       subSpecialty: "SubSpecialty 5",
//       topicsOfInterest: ["Topic 3", "Topic 4"],
//     },
//   },
//   {
//     firstName: "Frank",
//     lastName: "Zhang",
//     preferredName: "Frankie",
//     title: "Director",
//     designation: "Designation 6",
//     department: "Department 6",
//     contactNumber: "123-456-7890",
//     primaryBusinessEmail: "frank@example.com",
//     secondaryBusinessEmail: "",
//     alternativeEmail: "",
//     profilePhoto: "",
//     topicsOfInterest: ["Topic 3", "Topic 4"],
//     division: "Division 6",
//     specialty: "Specialty 2",
//     country: "USA",
//     divisionalContact: {
//       contactName: "Jane Lee",
//       division: "Division 6",
//       function: "Function 6",
//       phone: "123-456-7890",
//       specialty: "Specialty 1",
//       subSpecialty: "SubSpecialty 6",
//       topicsOfInterest: ["Topic 1", "Topic 2"],
//     },
//   },
//   {
//     firstName: "Grace",
//     lastName: "Chen",
//     preferredName: "Gracie",
//     title: "Manager",
//     designation: "Designation 7",
//     department: "Department 7",
//     contactNumber: "123-456-7890",
//     primaryBusinessEmail: "grace@example.com",
//     secondaryBusinessEmail: "",
//     alternativeEmail: "",
//     profilePhoto: "",
//     topicsOfInterest: ["Topic 1", "Topic 2"],
//     division: "Division 7",
//     specialty: "Specialty 1",
//     country: "USA",
//     divisionalContact: {
//       contactName: "John Chen",
//       division: "Division 7",
//       function: "Function 7",
//       phone: "123-456-7890",
//       specialty: "Specialty 2",
//       subSpecialty: "SubSpecialty 7",
//       topicsOfInterest: ["Topic 3", "Topic 4"],
//     },
//   },
//   {
//     firstName: "Henry",
//     lastName: "Wu",
//     preferredName: "Hank",
//     title: "Director",
//     designation: "Designation 8",
//     department: "Department 8",
//     contactNumber: "123-456-7890",
//     primaryBusinessEmail: "henry@example.com",
//     secondaryBusinessEmail: "",
//     alternativeEmail: "",
//     profilePhoto: "",
//     topicsOfInterest: ["Topic 3", "Topic 4"],
//     division: "Division 8",
//     specialty: "Specialty 2",
//     country: "USA",
//     divisionalContact: {
//       contactName: "Jane Chen",
//       division: "Division 8",
//       function: "Function 8",
//       phone: "123-456-7890",
//       specialty: "Specialty 1",
//       subSpecialty: "SubSpecialty 8",
//       topicsOfInterest: ["Topic 1", "Topic 2"],
//     },
//   },
//   {
//     firstName: "Isabella",
//     lastName: "Liu",
//     preferredName: "Izzy",
//     title: "Manager",
//     designation: "Designation 9",
//     department: "Department 9",
//     contactNumber: "123-456-7890",
//     primaryBusinessEmail: "isabella@example.com",
//     secondaryBusinessEmail: "",
//     alternativeEmail: "",
//     profilePhoto: "",
//     topicsOfInterest: ["Topic 1", "Topic 2"],
//     division: "Division 9",
//     specialty: "Specialty 1",
//     country: "USA",
//     divisionalContact: {
//       contactName: "John Liu",
//       division: "Division 9",
//       function: "Function 9",
//       phone: "123-456-7890",
//       specialty: "Specialty 2",
//       subSpecialty: "SubSpecialty 9",
//       topicsOfInterest: ["Topic 3", "Topic 4"],
//     },
//   },
//   {
//     firstName: "Jack",
//     lastName: "Chang",
//     preferredName: "Jackson",
//     title: "Director",
//     designation: "Designation 10",
//     department: "Department 10",
//     contactNumber: "123-456-7890",
//     primaryBusinessEmail: "jack@example.com",
//     secondaryBusinessEmail: "",
//     alternativeEmail: "",
//     profilePhoto: "",
//     topicsOfInterest: ["Topic 3", "Topic 4"],
//     division: "Division 10",
//     specialty: "Specialty 2",
//     country: "USA",
//     divisionalContact: {
//       contactName: "Jane Liu",
//       division: "Division 10",
//       function: "Function 10",
//       phone: "123-456-7890",
//       specialty: "Specialty 1",
//       subSpecialty: "SubSpecialty 10",
//       topicsOfInterest: ["Topic 1", "Topic 2"],
//     },
//   },
//   {
//     firstName: "Kate",
//     lastName: "Kim",
//     preferredName: "Katie",
//     title: "Manager",
//     designation: "Designation 11",
//     department: "Department 11",
//     contactNumber: "123-456-7890",
//     primaryBusinessEmail: "kate@example.com",
//     secondaryBusinessEmail: "",
//     alternativeEmail: "",
//     profilePhoto: "",
//     topicsOfInterest: ["Topic 1", "Topic 2"],
//     division: "Division 11",
//     specialty: "Specialty 1",
//     country: "USA",
//     divisionalContact: {
//       contactName: "John Kim",
//       division: "Division 11",
//       function: "Function 11",
//       phone: "123-456-7890",
//       specialty: "Specialty 2",
//       subSpecialty: "SubSpecialty 11",
//       topicsOfInterest: ["Topic 3", "Topic 4"],
//     },
//   },
//   {
//     firstName: "Leo",
//     lastName: "Park",
//     preferredName: "Leonardo",
//     title: "Director",
//     designation: "Designation 12",
//     department: "Department 12",
//     contactNumber: "123-456-7890",
//     primaryBusinessEmail: "leo@example.com",
//     secondaryBusinessEmail: "",
//     alternativeEmail: "",
//     profilePhoto: "",
//     topicsOfInterest: ["Topic 3", "Topic 4"],
//     division: "Division 12",
//     specialty: "Specialty 2",
//     country: "USA",
//     divisionalContact: {
//       contactName: "Jane Kim",
//       division: "Division 12",
//       function: "Function 12",
//       phone: "123-456-7890",
//       specialty: "Specialty 1",
//       subSpecialty: "SubSpecialty 12",
//       topicsOfInterest: ["Topic 1", "Topic 2"],
//     },
//   },
// ];
