import { Contact, DivisionalContact } from "@prisma/client";

type ActualContact = Omit<
  Contact,
  "id" | "createdAt" | "updatedAt" | "accountId"
> & {
  divisionalContact: Omit<DivisionalContact, "id" | "contactId">;
};

export const contacts: ActualContact[] = [
  {
    firstName: "John",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "John",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "John Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "john@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "John Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Jane",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Jane",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Jane Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "jane@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Jane Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Bob",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Bob",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Bob Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "bob@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Bob Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Alice",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Alice",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Alice Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "alice@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Alice Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "David",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "David",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "David Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "david@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "David Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Eva",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Eva",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Eva Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "eva@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Eva Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Frank",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Frank",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Frank Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "frank@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Frank Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Grace",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Grace",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Grace Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "grace@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Grace Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Henry",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Henry",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Henry Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "henry@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Henry Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Ivy",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Ivy",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Ivy Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "ivy@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Ivy Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Jack",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Jack",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Jack Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "jack@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Jack Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Karen",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Karen",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Karen Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "karen@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Karen Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Larry",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Larry",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Larry Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "larry@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Larry Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Megan",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Megan",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Megan Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "megan@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Megan Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Nick",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Nick",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Nick Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "nick@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Nick Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Olivia",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Olivia",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Olivia Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "olivia@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Olivia Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Paul",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Paul",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Paul Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "paul@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Paul Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Quinn",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Quinn",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Quinn Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "quinn@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Quinn Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Rachel",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Rachel",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Rachel Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "rachel@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Rachel Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Sam",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Sam",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Sam Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "sam@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Sam Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Tom",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Tom",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Tom Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "tom@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Tom Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Ursula",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Ursula",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Ursula Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "ursula@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Ursula Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Victor",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Victor",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Victor Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "victor@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Victor Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Wendy",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Wendy",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Wendy Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "wendy@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Wendy Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Xavier",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Xavier",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Xavier Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "xavier@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Xavier Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Yvonne",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Yvonne",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Yvonne Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "yvonne@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Yvonne Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Zach",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Zach",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Zach Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "zach@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Zach Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Amy",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Amy",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Amy Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "amy@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Amy Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Brian",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Brian",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Brian Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "brian@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Brian Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Carla",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Carla",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Carla Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "carla@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Carla Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Daniel",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Daniel",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Daniel Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "daniel@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Daniel Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Emily",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Emily",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Emily Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "emily@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Emily Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Fiona",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Fiona",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Fiona Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "fiona@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Fiona Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "George",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "George",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "George Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "george@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "George Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Hannah",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Hannah",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Hannah Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "hannah@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Hannah Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Ian",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Ian",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Ian Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "ian@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Ian Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Jennifer",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Jennifer",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Jennifer Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "jennifer@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Jennifer Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Kevin",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Kevin",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Kevin Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "kevin@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Kevin Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Linda",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Linda",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Linda Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "linda@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Linda Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Michael",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Michael",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Michael Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "michael@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Michael Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Nancy",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Nancy",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Nancy Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "nancy@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Nancy Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Oscar",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Oscar",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Oscar Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "oscar@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Oscar Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Peter",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Peter",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Peter Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "peter@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Peter Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Quincy",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Quincy",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Quincy Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "quincy@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Quincy Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Rachel",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Rachel",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Rachel Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "rachel@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Rachel Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Sam",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Sam",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Sam Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "sam@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Sam Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Tom",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Tom",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Tom Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "tom@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Tom Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Ursula",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Ursula",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Ursula Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "ursula@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Ursula Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Victor",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Victor",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Victor Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "victor@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Victor Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Wendy",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Wendy",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Wendy Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "wendy@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Wendy Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Xavier",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Xavier",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Xavier Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "xavier@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Xavier Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Yvonne",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Yvonne",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Yvonne Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "yvonne@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Yvonne Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Zach",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Zach",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Zach Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "zach@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Zach Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Amy",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Amy",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Amy Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "amy@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Amy Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Brian",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Brian",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Brian Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "brian@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Brian Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Carla",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Carla",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Carla Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "carla@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Carla Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Daniel",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Daniel",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Daniel Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "daniel@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Daniel Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Emily",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Emily",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Emily Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "emily@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Emily Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Fiona",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Fiona",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Fiona Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "fiona@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Fiona Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "George",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "George",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "George Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "george@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "George Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Hannah",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Hannah",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Hannah Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "hannah@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Hannah Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Ian",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Ian",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Ian Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "ian@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Ian Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Jennifer",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Jennifer",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Jennifer Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "jennifer@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Jennifer Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Kevin",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Kevin",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Kevin Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "kevin@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Kevin Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Linda",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Linda",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Linda Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "linda@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Linda Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Michael",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Michael",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Michael Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "michael@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Michael Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Nancy",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Nancy",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Nancy Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "nancy@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Nancy Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Oscar",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Oscar",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Oscar Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "oscar@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Oscar Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Peter",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Peter",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Peter Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "peter@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Peter Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Quincy",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Quincy",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Quincy Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "quincy@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Quincy Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Rachel",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Rachel",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Rachel Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "rachel@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Rachel Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Sam",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Sam",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Sam Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "sam@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Sam Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Tom",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Tom",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Tom Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "tom@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Tom Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Ursula",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Ursula",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Ursula Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "ursula@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Ursula Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Victor",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Victor",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Victor Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "victor@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Victor Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Wendy",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Wendy",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Wendy Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "wendy@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Wendy Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Xavier",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Xavier",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Xavier Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "xavier@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Xavier Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Yvonne",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Yvonne",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Yvonne Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "yvonne@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Yvonne Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Zach",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Zach",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Zach Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "zach@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Zach Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Amy",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Amy",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Amy Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "amy@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Amy Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Brian",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Brian",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Brian Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "brian@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Brian Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Carla",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Carla",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Carla Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "carla@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Carla Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Daniel",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Daniel",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Daniel Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "daniel@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Daniel Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Emily",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Emily",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Emily Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "emily@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Emily Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Fiona",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Fiona",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Fiona Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "fiona@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Fiona Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "George",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "George",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "George Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "george@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "George Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Hannah",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Hannah",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Hannah Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "hannah@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Hannah Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Ian",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Ian",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Ian Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "ian@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Ian Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Jennifer",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Jennifer",
    title: "Ms.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Jennifer Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "jennifer@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Jennifer Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
  {
    firstName: "Kevin",
    middleName: "Doe",
    lastName: "Smith",
    preferredName: "Kevin",
    title: "Mr.",
    designation: "Dr.",
    department: "Cardiology",
    bscBU: "CRM",
    bscRepName: "Kevin Doe",
    bscRepId: "1234567890",
    contactNumber: "1234567890",
    primaryBusinessEmail: "kevin@yopmail.com",
    secondaryBusinessEmail: "",
    comments: "",
    divisionalContact: {
      contactName: "Kevin Doe",
      division: "CRM",
      function: "Sales",
      specialty: "Cardiology",
      subSpecialty: "Electrophysiology",
      topicsOfInterest: ["Atherectomy Coronary"],
      phone: "1234567890",
    },
  },
];
