import { User } from "@prisma/client";

export const users: Omit<
  User,
  | "id"
  | "reportedById"
  | "costCenterId"
  | "territoryId"
  | "createdAt"
  | "updatedAt"
>[] = [
  {
    email: "user1@example.com",
    employeeName: "John Smith",
    jobTitle: "Software Engineer",
    division: "Engineering",
    azureADStatus: "Active",
    azureADId: "123456",
  },
  {
    email: "user2@example.com",
    employeeName: "Jane Doe",
    jobTitle: "Product Manager",
    division: "Product Management",
    azureADStatus: "Active",
    azureADId: "789012",
  },
  {
    email: "user3@example.com",
    employeeName: "Bob Johnson",
    jobTitle: "Data Analyst",
    division: "Data Analytics",
    azureADStatus: "Active",
    azureADId: "345678",
  },
  {
    email: "user4@example.com",
    employeeName: "Alice Brown",
    jobTitle: "UI Designer",
    division: "Design",
    azureADStatus: "Inactive",
    azureADId: "901234",
  },
  {
    email: "user5@example.com",
    employeeName: "David Lee",
    jobTitle: "HR Manager",
    division: "Human Resources",
    azureADStatus: "Active",
    azureADId: "567890",
  },
  {
    email: "user6@example.com",
    employeeName: "Eva Wilson",
    jobTitle: "Marketing Specialist",
    division: "Marketing",
    azureADStatus: "Active",
    azureADId: "234567",
  },
  {
    email: "user7@example.com",
    employeeName: "Frank Adams",
    jobTitle: "Financial Analyst",
    division: "Finance",
    azureADStatus: "Active",
    azureADId: "678901",
  },
  {
    email: "user8@example.com",
    employeeName: "Grace Taylor",
    jobTitle: "Sales Manager",
    division: "Sales",
    azureADStatus: "Active",
    azureADId: "789012",
  },
  {
    email: "user9@example.com",
    employeeName: "Harry Brown",
    jobTitle: "Customer Support",
    division: "Customer Service",
    azureADStatus: "Active",
    azureADId: "890123",
  },
  {
    email: "user10@example.com",
    employeeName: "Ivy Clark",
    jobTitle: "Operations Manager",
    division: "Operations",
    azureADStatus: "Active",
    azureADId: "345678",
  },
  {
    email: "user11@example.com",
    employeeName: "Jack White",
    jobTitle: "Data Scientist",
    division: "Data Analytics",
    azureADStatus: "Active",
    azureADId: "456789",
  },
  {
    email: "user12@example.com",
    employeeName: "Karen Davis",
    jobTitle: "UX Designer",
    division: "Design",
    azureADStatus: "Active",
    azureADId: "567890",
  },
  {
    email: "user13@example.com",
    employeeName: "Liam Johnson",
    jobTitle: "Research Analyst",
    division: "Research",
    azureADStatus: "Active",
    azureADId: "678901",
  },
  {
    email: "user14@example.com",
    employeeName: "Mia Adams",
    jobTitle: "Product Designer",
    division: "Design",
    azureADStatus: "Active",
    azureADId: "789012",
  },
  {
    email: "user15@example.com",
    employeeName: "Noah Brown",
    jobTitle: "QA Engineer",
    division: "Engineering",
    azureADStatus: "Active",
    azureADId: "890123",
  },
  {
    email: "user16@example.com",
    employeeName: "Olivia Taylor",
    jobTitle: "Marketing Manager",
    division: "Marketing",
    azureADStatus: "Active",
    azureADId: "901234",
  },
  {
    email: "user17@example.com",
    employeeName: "Patrick Wilson",
    jobTitle: "Financial Manager",
    division: "Finance",
    azureADStatus: "Active",
    azureADId: "234567",
  },
  {
    email: "user18@example.com",
    employeeName: "Quinn Clark",
    jobTitle: "Sales Representative",
    division: "Sales",
    azureADStatus: "Active",
    azureADId: "345678",
  },
  {
    email: "user19@example.com",
    employeeName: "Rachel Davis",
    jobTitle: "Customer Support",
    division: "Customer Service",
    azureADStatus: "Active",
    azureADId: "456789",
  },
  {
    email: "user20@example.com",
    employeeName: "Samuel White",
    jobTitle: "Operations Specialist",
    division: "Operations",
    azureADStatus: "Active",
    azureADId: "567890",
  },
];
