// import { User } from "@prisma/client";

// export const users: Omit<
//   User,
//   | "id"
//   | "reportedById"
//   | "costCenterId"
//   | "territoryId"
//   | "createdAt"
//   | "updatedAt"
// >[] = [
//   {
//     email: "user1@example.com",
//     firstName: "John",
//     lastName: "Smith",
//     jobTitle: "Software Engineer",
//     division: "Engineering",
//     azureADStatus: "Active",
//     azureADId: "123456",
//   },
//   {
//     email: "user2@example.com",
//     firstName: "Jane Doe",
//     lastName: "Smith",
//     jobTitle: "Product Manager",
//     division: "Product Management",
//     azureADStatus: "Active",
//     azureADId: "789012",
//   },
//   {
//     email: "user3@example.com",
//     firstName: "Bob Johnson",
//     lastName: "Smith",
//     jobTitle: "Data Analyst",
//     division: "Data Analytics",
//     azureADStatus: "Active",
//     azureADId: "345678",
//   },
//   {
//     email: "user4@example.com",
//     firstName: "Alice Brown",
//     lastName: "Smith",
//     jobTitle: "UI Designer",
//     division: "Design",
//     azureADStatus: "Inactive",
//     azureADId: "901234",
//   },
//   {
//     email: "user5@example.com",
//     firstName: "David Lee",
//     lastName: "Smith",
//     jobTitle: "HR Manager",
//     division: "Human Resources",
//     azureADStatus: "Active",
//     azureADId: "567890",
//   },
//   {
//     email: "user6@example.com",
//     firstName: "Eva Wilson",
//     lastName: "Smith",
//     jobTitle: "Marketing Specialist",
//     division: "Marketing",
//     azureADStatus: "Active",
//     azureADId: "234567",
//   },
//   {
//     email: "user7@example.com",
//     firstName: "Frank Adams",
//     lastName: "Smith",
//     jobTitle: "Financial Analyst",
//     division: "Finance",
//     azureADStatus: "Active",
//     azureADId: "678901",
//   },
//   {
//     email: "user8@example.com",
//     firstName: "Grace Taylor",
//     lastName: "Smith",
//     jobTitle: "Sales Manager",
//     division: "Sales",
//     azureADStatus: "Active",
//     azureADId: "789012",
//   },
//   {
//     email: "user9@example.com",
//     firstName: "Harry Brown",
//     lastName: "Smith",
//     jobTitle: "Customer Support",
//     division: "Customer Service",
//     azureADStatus: "Active",
//     azureADId: "890123",
//   },
//   {
//     email: "user10@example.com",
//     firstName: "Ivy Clark",
//     lastName: "Smith",
//     jobTitle: "Operations Manager",
//     division: "Operations",
//     azureADStatus: "Active",
//     azureADId: "345678",
//   },
//   {
//     email: "user11@example.com",
//     firstName: "Jack White",
//     lastName: "Smith",
//     jobTitle: "Data Scientist",
//     division: "Data Analytics",
//     azureADStatus: "Active",
//     azureADId: "456789",
//   },
//   {
//     email: "user12@example.com",
//     firstName: "Karen Davis",
//     lastName: "Smith",
//     jobTitle: "UX Designer",
//     division: "Design",
//     azureADStatus: "Active",
//     azureADId: "567890",
//   },
//   {
//     email: "user13@example.com",
//     firstName: "Liam Johnson",
//     lastName: "Smith",
//     jobTitle: "Research Analyst",
//     division: "Research",
//     azureADStatus: "Active",
//     azureADId: "678901",
//   },
//   {
//     email: "user14@example.com",
//     firstName: "Mia Adams",
//     lastName: "Smith",
//     jobTitle: "Product Designer",
//     division: "Design",
//     azureADStatus: "Active",
//     azureADId: "789012",
//   },
//   {
//     email: "user15@example.com",
//     firstName: "Noah Brown",
//     lastName: "Smith",
//     jobTitle: "QA Engineer",
//     division: "Engineering",
//     azureADStatus: "Active",
//     azureADId: "890123",
//   },
//   {
//     email: "user16@example.com",
//     firstName: "Olivia Taylor",
//     lastName: "Smith",
//     jobTitle: "Marketing Manager",
//     division: "Marketing",
//     azureADStatus: "Active",
//     azureADId: "901234",
//   },
//   {
//     email: "user17@example.com",
//     firstName: "Patrick Wilson",
//     lastName: "Smith",
//     jobTitle: "Financial Manager",
//     division: "Finance",
//     azureADStatus: "Active",
//     azureADId: "234567",
//   },
//   {
//     email: "user18@example.com",
//     firstName: "Quinn Clark",
//     lastName: "Smith",
//     jobTitle: "Sales Representative",
//     division: "Sales",
//     azureADStatus: "Active",
//     azureADId: "345678",
//   },
//   {
//     email: "user19@example.com",
//     firstName: "Rachel Davis",
//     lastName: "Smith",
//     jobTitle: "Customer Support",
//     division: "Customer Service",
//     azureADStatus: "Active",
//     azureADId: "456789",
//   },
//   {
//     email: "user20@example.com",
//     firstName: "Samuel White",
//     lastName: "Smith",
//     jobTitle: "Operations Specialist",
//     division: "Operations",
//     azureADStatus: "Active",
//     azureADId: "567890",
//   },
// ];
