apiVersion: v1
kind: Pod
metadata:
  name: rds-forwarder
  labels:
    run: rds-forwarder
spec:
  imagePullSecrets:
    - name: dockerhub-image-pull-secret
  containers:
    - name: rds-forwarder
      image: alpine/socat
      command: ['sh', '-c']
      args:
        - socat tcp-listen:5432,fork,reuseaddr tcp-connect:jarvis-mark.cqm2o1je3mup.us-east-1.rds.amazonaws.com:5432
      ports:
        - containerPort: 5432